import type { AppleWatchModel } from "../product-data";
import { fact, type ProductTechnicalSpecCatalog } from "./types";

type HistoricalAppleWatchModel = Exclude<
  AppleWatchModel,
  "apple-watch-series-11" | "apple-watch-ultra-3" | "apple-watch-se-3"
>;

export const historicalAppleWatchTechnicalSpecs = {
  "apple-watch-series-10": {
    introduced: "2024",
    sourceUrl: "https://support.apple.com/en-us/121202",
    fields: {
      finishes: fact("Aluminum: Jet Black, Rose Gold, Silver; titanium: Slate, Gold, Natural", "Nhôm: Đen Bóng, Vàng Hồng, Bạc; titanium: Slate, Vàng, Tự Nhiên"),
      capacity: "64GB",
      dimensions: fact("42mm or 46mm case; 9.7 mm deep; from 30 g depending on size, material, and connectivity", "Vỏ 42 mm hoặc 46 mm; dày 9,7 mm; từ 30 g tùy kích thước, vật liệu và kết nối"),
      display: fact("Always-On wide-angle LTPO3 OLED; 1–2000 nits; 374×446 (42mm) or 416×496 (46mm)", "OLED LTPO3 góc rộng Always-On; 1–2.000 nit; 374×446 (42 mm) hoặc 416×496 (46 mm)"),
      chip: fact("S10 dual-core 64-bit chip; 4-core Neural Engine", "S10 hai lõi 64-bit; Neural Engine 4 lõi"),
      sensors: fact("Electrical and third-generation optical heart sensors, blood oxygen, temperature, depth, water temperature, compass, altimeter, and motion sensors", "Cảm biến tim điện và quang học thế hệ 3, oxy máu, nhiệt độ, độ sâu, nhiệt độ nước, la bàn, cao độ và chuyển động"),
      battery: fact("Up to 18 hours normal use; up to 36 hours in Low Power Mode", "Đến 18 giờ sử dụng thường; đến 36 giờ ở Chế Độ Nguồn Điện Thấp"),
      charging: fact("Up to 80% in about 30 minutes; 15 minutes gives up to 8 hours", "Đến 80% trong khoảng 30 phút; sạc 15 phút dùng đến 8 giờ"),
      durability: "WR50 swimproof; IP6X dust resistant",
      connectivity: "Wi‑Fi 4, Bluetooth 5.3, L1 GPS, second-generation UWB; optional LTE",
      compatibility: fact("Requires a compatible iPhone and current supported software; health features vary by region", "Cần iPhone tương thích và phiên bản phần mềm còn được hỗ trợ; tính năng sức khỏe thay đổi theo khu vực"),
    },
  },
  "apple-watch-series-9": {
    introduced: "2023",
    sourceUrl: "https://support.apple.com/en-us/111833",
    fields: {
      finishes: fact("Aluminum: Pink, Midnight, Starlight, Silver, (PRODUCT)RED; stainless steel: Gold, Silver, Graphite", "Nhôm: Hồng, Midnight, Starlight, Bạc, (PRODUCT)RED; thép không gỉ: Vàng, Bạc, Graphite"),
      capacity: "64GB",
      dimensions: fact("41mm or 45mm case; 10.7 mm deep; from 31.9 g depending on size, material, and connectivity", "Vỏ 41 mm hoặc 45 mm; dày 10,7 mm; từ 31,9 g tùy kích thước, vật liệu và kết nối"),
      display: fact("Always-On LTPO OLED; 1–2000 nits; 352×430 (41mm) or 396×484 (45mm)", "OLED LTPO Always-On; 1–2.000 nit; 352×430 (41 mm) hoặc 396×484 (45 mm)"),
      chip: fact("S9 dual-core 64-bit chip; 4-core Neural Engine", "S9 hai lõi 64-bit; Neural Engine 4 lõi"),
      sensors: fact("Electrical and third-generation optical heart sensors, blood oxygen, temperature, compass, always-on altimeter, and motion sensors", "Cảm biến tim điện và quang học thế hệ 3, oxy máu, nhiệt độ, la bàn, cao độ luôn bật và chuyển động"),
      battery: fact("Up to 18 hours normal use; up to 36 hours in Low Power Mode", "Đến 18 giờ sử dụng thường; đến 36 giờ ở Chế Độ Nguồn Điện Thấp"),
      charging: fact("Up to 80% in about 45 minutes; 8 minutes enables about 8 hours of sleep tracking", "Đến 80% trong khoảng 45 phút; sạc 8 phút đủ cho khoảng 8 giờ theo dõi giấc ngủ"),
      durability: "WR50 swimproof; IP6X dust resistant",
      connectivity: "Wi‑Fi 4, Bluetooth 5.3, L1 GPS, second-generation UWB; optional LTE",
      compatibility: fact("Requires a compatible iPhone and current supported software; health features vary by region", "Cần iPhone tương thích và phiên bản phần mềm còn được hỗ trợ; tính năng sức khỏe thay đổi theo khu vực"),
    },
  },
  "apple-watch-series-8": {
    introduced: "2022",
    sourceUrl: "https://support.apple.com/en-us/111848",
    fields: {
      finishes: fact("Aluminum: Midnight, Starlight, Silver, (PRODUCT)RED; stainless steel: Graphite, Silver, Gold", "Nhôm: Midnight, Starlight, Bạc, (PRODUCT)RED; thép không gỉ: Graphite, Bạc, Vàng"),
      capacity: "32GB",
      dimensions: fact("41mm or 45mm case; 10.7 mm deep; from 32 g depending on size, material, and connectivity", "Vỏ 41 mm hoặc 45 mm; dày 10,7 mm; từ 32 g tùy kích thước, vật liệu và kết nối"),
      display: fact("Always-On LTPO OLED; up to 1000 nits; 352×430 (41mm) or 396×484 (45mm)", "OLED LTPO Always-On; đến 1.000 nit; 352×430 (41 mm) hoặc 396×484 (45 mm)"),
      chip: fact("S8 dual-core 64-bit chip; W3 wireless chip; U1 ultra-wideband chip", "S8 hai lõi 64-bit; chip không dây W3; chip băng thông siêu rộng U1"),
      sensors: fact("Electrical and third-generation optical heart sensors, blood oxygen, temperature, compass, altimeter, and motion sensors", "Cảm biến tim điện và quang học thế hệ 3, oxy máu, nhiệt độ, la bàn, cao độ và chuyển động"),
      battery: fact("Up to 18 hours normal use", "Đến 18 giờ sử dụng thường"),
      charging: fact("Fast charging with the Apple USB‑C magnetic fast-charging cable", "Sạc nhanh bằng cáp sạc nhanh từ tính Apple USB‑C"),
      durability: "WR50 swimproof; IP6X dust resistant",
      connectivity: "Wi‑Fi 4, Bluetooth 5.3, GPS/GNSS, U1; optional LTE/UMTS",
      compatibility: fact("Requires a compatible iPhone and supported software; health features vary by region", "Cần iPhone tương thích và phần mềm được hỗ trợ; tính năng sức khỏe thay đổi theo khu vực"),
    },
  },
  "apple-watch-series-7": {
    introduced: "2021",
    sourceUrl: "https://support.apple.com/en-us/111909",
    fields: {
      finishes: fact("Aluminum: Midnight, Starlight, Green, Blue, (PRODUCT)RED; stainless steel: Graphite, Silver, Gold; titanium: Space Black, Titanium", "Nhôm: Midnight, Starlight, Xanh Lá, Xanh Dương, (PRODUCT)RED; thép không gỉ: Graphite, Bạc, Vàng; titanium: Đen Không Gian, Titanium"),
      capacity: "32GB",
      dimensions: fact("41mm or 45mm case; 10.7 mm deep; from 32 g depending on size, material, and connectivity", "Vỏ 41 mm hoặc 45 mm; dày 10,7 mm; từ 32 g tùy kích thước, vật liệu và kết nối"),
      display: fact("Always-On LTPO OLED; up to 1000 nits; 352×430 (41mm) or 396×484 (45mm)", "OLED LTPO Always-On; đến 1.000 nit; 352×430 (41 mm) hoặc 396×484 (45 mm)"),
      chip: fact("S7 dual-core 64-bit chip; W3 wireless chip; U1 ultra-wideband chip", "S7 hai lõi 64-bit; chip không dây W3; chip băng thông siêu rộng U1"),
      sensors: fact("Electrical and third-generation optical heart sensors, blood oxygen, compass, always-on altimeter, and motion sensors", "Cảm biến tim điện và quang học thế hệ 3, oxy máu, la bàn, cao độ luôn bật và chuyển động"),
      battery: fact("Up to 18 hours normal use", "Đến 18 giờ sử dụng thường"),
      charging: fact("Fast charging with the Apple USB‑C magnetic fast-charging cable", "Sạc nhanh bằng cáp sạc nhanh từ tính Apple USB‑C"),
      durability: "WR50 swimproof; IP6X dust resistant",
      connectivity: "Wi‑Fi 4, Bluetooth 5.0, GPS/GNSS, U1; optional LTE/UMTS",
      compatibility: fact("Requires a compatible iPhone and supported software; health features vary by region", "Cần iPhone tương thích và phần mềm được hỗ trợ; tính năng sức khỏe thay đổi theo khu vực"),
    },
  },
  "apple-watch-series-6": {
    introduced: "2020",
    sourceUrl: "https://support.apple.com/en-us/111918",
    fields: {
      finishes: fact("Aluminum, stainless steel, or titanium case; colors vary by material", "Vỏ nhôm, thép không gỉ hoặc titanium; màu sắc thay đổi theo vật liệu"),
      capacity: "32GB",
      dimensions: fact("40mm or 44mm case; 10.7 mm deep; from 30.5 g depending on size and material", "Vỏ 40 mm hoặc 44 mm; dày 10,7 mm; từ 30,5 g tùy kích thước và vật liệu"),
      display: fact("Always-On LTPO OLED; up to 1000 nits; 324×394 (40mm) or 368×448 (44mm)", "OLED LTPO Always-On; đến 1.000 nit; 324×394 (40 mm) hoặc 368×448 (44 mm)"),
      chip: fact("S6 dual-core 64-bit chip; W3 wireless chip; U1 ultra-wideband chip", "S6 hai lõi 64-bit; chip không dây W3; chip băng thông siêu rộng U1"),
      sensors: fact("Blood oxygen, electrical and third-generation optical heart sensors, compass, always-on altimeter, and motion sensors", "Cảm biến oxy máu, tim điện và quang học thế hệ 3, la bàn, cao độ luôn bật và chuyển động"),
      battery: fact("Up to 18 hours normal use", "Đến 18 giờ sử dụng thường"),
      charging: fact("Apple magnetic charging cable", "Cáp sạc từ tính Apple"),
      durability: "WR50 swimproof",
      connectivity: "Dual-band Wi‑Fi, Bluetooth 5.0, GPS/GNSS, U1; optional LTE/UMTS",
      compatibility: fact("Requires a compatible iPhone and supported software; health features vary by region", "Cần iPhone tương thích và phần mềm được hỗ trợ; tính năng sức khỏe thay đổi theo khu vực"),
    },
  },
  "apple-watch-series-5": {
    introduced: "2019",
    sourceUrl: "https://support.apple.com/en-us/118453",
    fields: {
      finishes: fact("Aluminum, stainless steel, titanium, or ceramic case; colors vary by material", "Vỏ nhôm, thép không gỉ, titanium hoặc gốm; màu sắc thay đổi theo vật liệu"),
      capacity: "32GB",
      dimensions: fact("40mm or 44mm case; 10.74 mm deep; from 30.8 g depending on size and material", "Vỏ 40 mm hoặc 44 mm; dày 10,74 mm; từ 30,8 g tùy kích thước và vật liệu"),
      display: fact("Always-On LTPO OLED Retina display; up to 1000 nits", "Màn hình Retina OLED LTPO Always-On; đến 1.000 nit"),
      chip: fact("S5 dual-core 64-bit chip; W3 wireless chip", "S5 hai lõi 64-bit; chip không dây W3"),
      sensors: fact("Electrical and second-generation optical heart sensors, compass, barometric altimeter, and motion sensors", "Cảm biến tim điện và quang học thế hệ 2, la bàn, cao độ khí áp và chuyển động"),
      battery: fact("Up to 18 hours normal use", "Đến 18 giờ sử dụng thường"),
      charging: fact("Apple magnetic charging cable", "Cáp sạc từ tính Apple"),
      durability: "WR50 swimproof",
      connectivity: "Wi‑Fi, Bluetooth 5.0, GPS/GNSS; optional LTE/UMTS",
      compatibility: fact("Requires a compatible iPhone and supported software; feature availability depends on software and region", "Cần iPhone tương thích và phần mềm được hỗ trợ; tính năng phụ thuộc phần mềm và khu vực"),
    },
  },
  "apple-watch-series-3": {
    introduced: "2017",
    sourceUrl: "https://support.apple.com/en-us/111891",
    fields: {
      finishes: fact("Silver or Space Gray aluminum; stainless-steel and ceramic finishes on cellular configurations", "Nhôm màu Bạc hoặc Xám Không Gian; bản di động có thêm hoàn thiện thép không gỉ và gốm"),
      capacity: fact("8GB on GPS models; 16GB on GPS + Cellular models", "8GB trên bản GPS; 16GB trên bản GPS + Cellular"),
      dimensions: fact("38mm or 42mm case; 11.4 mm deep; from 26.7 g depending on size, material, and connectivity", "Vỏ 38 mm hoặc 42 mm; dày 11,4 mm; từ 26,7 g tùy kích thước, vật liệu và kết nối"),
      display: fact("Second-generation OLED Retina display with Force Touch; up to 1000 nits", "Màn hình Retina OLED thế hệ 2 với Force Touch; đến 1.000 nit"),
      chip: fact("S3 dual-core processor; W2 wireless chip", "Bộ xử lý S3 hai lõi; chip không dây W2"),
      sensors: fact("Optical heart sensor, barometric altimeter, accelerometer, gyroscope, and ambient light sensor", "Cảm biến tim quang học, cao độ khí áp, gia tốc kế, con quay hồi chuyển và ánh sáng môi trường"),
      battery: fact("Up to 18 hours normal use", "Đến 18 giờ sử dụng thường"),
      charging: fact("Apple magnetic charging cable with USB‑A", "Cáp sạc từ tính Apple với USB‑A"),
      durability: "WR50 swimproof",
      connectivity: "Wi‑Fi, Bluetooth 4.2, GPS/GLONASS/Galileo/QZSS; optional LTE/UMTS",
      compatibility: fact("Software and iPhone compatibility are limited by this model’s final supported watchOS release", "Khả năng tương thích phần mềm và iPhone bị giới hạn bởi phiên bản watchOS cuối cùng hỗ trợ model này"),
    },
  },
  "apple-watch-ultra-2": {
    introduced: "2023",
    sourceUrl: "https://support.apple.com/en-us/111832",
    fields: {
      finishes: fact("Natural or Black Grade 5 titanium", "Titanium Grade 5 màu Tự Nhiên hoặc Đen"),
      capacity: "64GB",
      dimensions: fact("49 × 44 × 12 mm; 61.4 g Natural or 61.8 g Black", "49 × 44 × 12 mm; 61,4 g màu Tự Nhiên hoặc 61,8 g màu Đen"),
      display: fact("Always-On LTPO2 OLED; 410×502; up to 3000 nits; sapphire crystal", "OLED LTPO2 Always-On; 410×502; đến 3.000 nit; kính sapphire"),
      chip: fact("S9 dual-core 64-bit chip; 4-core Neural Engine", "S9 hai lõi 64-bit; Neural Engine 4 lõi"),
      sensors: fact("Electrical and third-generation optical heart sensors, blood oxygen, temperature, depth, water temperature, precision dual-frequency GPS, altimeter, and compass", "Cảm biến tim điện và quang học thế hệ 3, oxy máu, nhiệt độ, độ sâu, nhiệt độ nước, GPS hai tần số chính xác, cao độ và la bàn"),
      battery: fact("Up to 36 hours normal use; up to 72 hours in Low Power Mode", "Đến 36 giờ sử dụng thường; đến 72 giờ ở Chế Độ Nguồn Điện Thấp"),
      charging: fact("Up to 80% in about 1 hour; fast charging with Apple USB‑C magnetic cable", "Đến 80% trong khoảng 1 giờ; sạc nhanh bằng cáp từ tính Apple USB‑C"),
      durability: fact("WR100; recreational scuba to 40 m; IP6X; MIL‑STD 810H tested", "WR100; lặn giải trí đến 40 m; IP6X; thử nghiệm theo MIL‑STD 810H"),
      connectivity: "Wi‑Fi 4, Bluetooth 5.3, precision dual-frequency GPS, second-generation UWB, LTE/UMTS",
      compatibility: fact("Requires a compatible iPhone and current supported software; health features vary by region", "Cần iPhone tương thích và phiên bản phần mềm còn được hỗ trợ; tính năng sức khỏe thay đổi theo khu vực"),
    },
  },
  "apple-watch-ultra": {
    introduced: "2022",
    sourceUrl: "https://support.apple.com/en-us/111852",
    fields: {
      finishes: fact("Natural aerospace-grade titanium", "Titanium cấp hàng không vũ trụ màu Tự Nhiên"),
      capacity: "32GB",
      dimensions: fact("49 × 44 × 12 mm; 61.3 g", "49 × 44 × 12 mm; 61,3 g"),
      display: fact("Always-On LTPO2 OLED; 410×502; up to 2000 nits; sapphire crystal", "OLED LTPO2 Always-On; 410×502; đến 2.000 nit; kính sapphire"),
      chip: fact("S8 dual-core 64-bit chip; W3 wireless chip; U1 ultra-wideband chip", "S8 hai lõi 64-bit; chip không dây W3; chip băng thông siêu rộng U1"),
      sensors: fact("Electrical and third-generation optical heart sensors, blood oxygen, temperature, depth, water temperature, precision dual-frequency GPS, altimeter, and compass", "Cảm biến tim điện và quang học thế hệ 3, oxy máu, nhiệt độ, độ sâu, nhiệt độ nước, GPS hai tần số chính xác, cao độ và la bàn"),
      battery: fact("Up to 36 hours normal use", "Đến 36 giờ sử dụng thường"),
      charging: fact("Fast charging with Apple USB‑C magnetic cable", "Sạc nhanh bằng cáp từ tính Apple USB‑C"),
      durability: fact("WR100; recreational scuba to 40 m; IP6X; MIL‑STD 810H tested", "WR100; lặn giải trí đến 40 m; IP6X; thử nghiệm theo MIL‑STD 810H"),
      connectivity: "Wi‑Fi 4, Bluetooth 5.3, precision dual-frequency GPS, U1, LTE/UMTS",
      compatibility: fact("Requires a compatible iPhone and supported software; health features vary by region", "Cần iPhone tương thích và phần mềm được hỗ trợ; tính năng sức khỏe thay đổi theo khu vực"),
    },
  },
  "apple-watch-se": {
    introduced: "2020",
    sourceUrl: "https://support.apple.com/en-us/111862",
    fields: {
      finishes: fact("Gold, Silver, or Space Gray aluminum", "Nhôm màu Vàng, Bạc hoặc Xám Không Gian"),
      capacity: "32GB",
      dimensions: fact("40mm or 44mm case; 10.7 mm deep; from 30.5 g depending on size and connectivity", "Vỏ 40 mm hoặc 44 mm; dày 10,7 mm; từ 30,5 g tùy kích thước và kết nối"),
      display: fact("LTPO OLED Retina display; up to 1000 nits; 324×394 (40mm) or 368×448 (44mm)", "Màn hình Retina OLED LTPO; đến 1.000 nit; 324×394 (40 mm) hoặc 368×448 (44 mm)"),
      chip: fact("S5 dual-core 64-bit chip; W3 wireless chip", "S5 hai lõi 64-bit; chip không dây W3"),
      sensors: fact("Second-generation optical heart sensor, compass, always-on altimeter, and motion sensors", "Cảm biến tim quang học thế hệ 2, la bàn, cao độ luôn bật và chuyển động"),
      battery: fact("Up to 18 hours normal use", "Đến 18 giờ sử dụng thường"),
      charging: fact("Apple magnetic charging cable", "Cáp sạc từ tính Apple"),
      durability: "WR50 swimproof; Ion‑X front glass",
      connectivity: "Wi‑Fi, Bluetooth 5.0, GPS/GNSS; optional LTE/UMTS",
      compatibility: fact("Requires a compatible iPhone and supported software; feature availability depends on software and region", "Cần iPhone tương thích và phần mềm được hỗ trợ; tính năng phụ thuộc phần mềm và khu vực"),
    },
  },
} as const satisfies Pick<ProductTechnicalSpecCatalog, HistoricalAppleWatchModel>;
