import type { IpadModel } from "../product-data";
import { fact, type ProductTechnicalSpecCatalog } from "./types";

export const ipadTechnicalSpecs = {
  "ipad-pro-m5": {
    introduced: "2025",
    sourceUrl: "https://www.apple.com/ipad-pro/specs/",
    fields: {
      finishes: fact("Silver or Space Black; recycled aluminum enclosure", "Bạc hoặc Space Black; vỏ nhôm tái chế"),
      capacity: "256GB / 512GB / 1TB / 2TB",
      dimensions: fact("11-inch: 249.7 × 177.5 × 5.3 mm, 444 g; 13-inch: 281.6 × 215.5 × 5.1 mm, 579 g (Wi‑Fi)", "11 inch: 249,7 × 177,5 × 5,3 mm, 444 g; 13 inch: 281,6 × 215,5 × 5,1 mm, 579 g (Wi‑Fi)"),
      display: fact("11- or 13-inch Ultra Retina XDR Tandem OLED; ProMotion 10–120Hz; 1000 nits full-screen, 1600 nits peak HDR; nano-texture option on 1TB/2TB", "Ultra Retina XDR Tandem OLED 11 hoặc 13 inch; ProMotion 10–120Hz; 1.000 nit toàn màn hình, 1.600 nit HDR; tùy chọn kính nano-texture trên bản 1TB/2TB"),
      chip: fact("M5: 9- or 10-core CPU, 10-core GPU with Neural Accelerators, 16-core Neural Engine", "M5: CPU 9 hoặc 10 lõi, GPU 10 lõi có Neural Accelerator, Neural Engine 16 lõi"),
      memory: fact("12GB unified memory on 256/512GB; 16GB on 1/2TB", "Bộ nhớ thống nhất 12GB trên bản 256/512GB; 16GB trên bản 1/2TB"),
      camera: "12MP Wide, LiDAR, Adaptive True Tone flash; 4K and ProRes video",
      frontCamera: "Landscape 12MP Center Stage TrueDepth camera",
      audio: fact("Four speakers and studio-quality four-microphone array", "Bốn loa và cụm bốn micro chuẩn studio"),
      battery: fact("Up to 10 hours web or video on Wi‑Fi; up to 9 hours on cellular", "Đến 10 giờ duyệt web hoặc xem video qua Wi‑Fi; 9 giờ qua mạng di động"),
      charging: fact("Fast charge to 50% in about 30 minutes with a 60W-or-higher adapter", "Sạc nhanh 50% trong khoảng 30 phút với bộ sạc từ 60W"),
      connectivity: "Wi‑Fi 7, Bluetooth 6, Thread; optional 5G with Apple C1X modem and eSIM",
      ports: "Thunderbolt / USB 4 up to 40Gb/s; DisplayPort",
      authentication: "Face ID",
      accessories: "Apple Pencil Pro, Apple Pencil (USB‑C), Magic Keyboard",
    },
  },
  "ipad-air-m4": {
    introduced: "2026",
    sourceUrl: "https://www.apple.com/ipad-air/specs/",
    fields: {
      finishes: fact("Blue, Purple, Starlight, Space Gray; aluminum", "Xanh Dương, Tím, Ánh Sao, Xám Không Gian; nhôm"),
      capacity: "128GB / 256GB / 512GB / 1TB",
      dimensions: fact("11-inch: 247.6 × 178.5 × 6.1 mm, 464 g; 13-inch: 280.6 × 214.9 × 6.1 mm, 616 g (Wi‑Fi)", "11 inch: 247,6 × 178,5 × 6,1 mm, 464 g; 13 inch: 280,6 × 214,9 × 6,1 mm, 616 g (Wi‑Fi)"),
      display: fact("11-inch 2360×1640 at 500 nits or 13-inch 2732×2048 at 600 nits; laminated P3 Liquid Retina", "Liquid Retina P3 ép lớp: 11 inch 2360×1640, 500 nit hoặc 13 inch 2732×2048, 600 nit"),
      chip: fact("M4: 8-core CPU, 9-core GPU, 16-core Neural Engine, 120GB/s memory bandwidth", "M4: CPU 8 lõi, GPU 9 lõi, Neural Engine 16 lõi, băng thông bộ nhớ 120GB/s"),
      memory: "12GB unified memory",
      camera: "12MP Wide; 4K video up to 60 fps",
      frontCamera: "Landscape 12MP Center Stage camera",
      audio: fact("Landscape stereo speakers and dual microphones", "Loa stereo ngang và hai micro"),
      battery: fact("Up to 10 hours web or video on Wi‑Fi; up to 9 hours on cellular", "Đến 10 giờ duyệt web hoặc xem video qua Wi‑Fi; 9 giờ qua mạng di động"),
      connectivity: "Wi‑Fi 7, Bluetooth 6, Thread; optional 5G with Apple C1X modem and eSIM",
      ports: "USB‑C with USB 3 up to 10Gb/s; DisplayPort up to 6K/60Hz",
      authentication: "Touch ID in the top button",
      accessories: "Apple Pencil Pro, Apple Pencil (USB‑C), Magic Keyboard",
    },
  },
  "ipad-a16": {
    introduced: "2025",
    sourceUrl: "https://www.apple.com/ipad-11/specs/",
    fields: {
      finishes: fact("Silver, Blue, Pink, Yellow; aluminum", "Bạc, Xanh Dương, Hồng, Vàng; nhôm"),
      capacity: "128GB / 256GB / 512GB",
      dimensions: fact("248.6 × 179.5 × 7.0 mm; 477 g Wi‑Fi or 481 g Cellular", "248,6 × 179,5 × 7,0 mm; 477 g bản Wi‑Fi hoặc 481 g bản Cellular"),
      display: fact("10.86-inch Liquid Retina, 2360×1640 at 264 ppi; 500 nits, True Tone", "Liquid Retina 10,86 inch, 2360×1640, 264 ppi; 500 nit, True Tone"),
      chip: fact("A16: 5-core CPU, 4-core GPU, 16-core Neural Engine", "A16: CPU 5 lõi, GPU 4 lõi, Neural Engine 16 lõi"),
      camera: "12MP Wide; 4K video up to 60 fps",
      frontCamera: "Landscape 12MP Center Stage camera",
      audio: fact("Landscape stereo speakers and dual microphones", "Loa stereo ngang và hai micro"),
      battery: fact("Up to 10 hours web or video on Wi‑Fi; up to 9 hours on cellular", "Đến 10 giờ duyệt web hoặc xem video qua Wi‑Fi; 9 giờ qua mạng di động"),
      connectivity: "Wi‑Fi 6, Bluetooth 5.3; optional 5G and eSIM",
      ports: "USB‑C with USB 2 up to 480Mb/s; DisplayPort up to 4K/60Hz",
      authentication: "Touch ID in the top button",
      accessories: "Apple Pencil (USB‑C), Apple Pencil (1st generation), Magic Keyboard Folio",
    },
  },
  "ipad-mini-a17-pro": {
    introduced: "2024",
    sourceUrl: "https://www.apple.com/ipad-mini/specs/",
    fields: {
      finishes: fact("Blue, Purple, Starlight, Space Gray; aluminum", "Xanh Dương, Tím, Ánh Sao, Xám Không Gian; nhôm"),
      capacity: "128GB / 256GB / 512GB",
      dimensions: fact("195.4 × 134.8 × 6.3 mm; 293 g Wi‑Fi or 297 g Cellular", "195,4 × 134,8 × 6,3 mm; 293 g bản Wi‑Fi hoặc 297 g bản Cellular"),
      display: fact("8.3-inch Liquid Retina, 2266×1488 at 326 ppi; 500 nits, P3, fully laminated", "Liquid Retina 8,3 inch, 2266×1488, 326 ppi; 500 nit, P3, ép lớp toàn phần"),
      chip: fact("A17 Pro: 6-core CPU, 5-core GPU, 16-core Neural Engine", "A17 Pro: CPU 6 lõi, GPU 5 lõi, Neural Engine 16 lõi"),
      camera: "12MP Wide with True Tone flash; 4K video up to 60 fps",
      frontCamera: "12MP Center Stage camera",
      audio: fact("Landscape stereo speakers and dual microphones", "Loa stereo ngang và hai micro"),
      battery: fact("Up to 10 hours web or video on Wi‑Fi; up to 9 hours on cellular", "Đến 10 giờ duyệt web hoặc xem video qua Wi‑Fi; 9 giờ qua mạng di động"),
      connectivity: "Wi‑Fi 6E, Bluetooth 5.3; optional 5G and eSIM",
      ports: "USB‑C with USB 3 up to 10Gb/s; DisplayPort",
      authentication: "Touch ID in the top button",
      accessories: "Apple Pencil Pro, Apple Pencil (USB‑C)",
    },
  },
} as const satisfies Pick<ProductTechnicalSpecCatalog, IpadModel>;
