import type { Iphone14Model, Iphone15Model, Iphone16Model, Iphone17Model, LegacyModel } from "../product-data";
import { fact, type ProductTechnicalSpecCatalog } from "./types";

type IphoneModel = LegacyModel | Iphone17Model | Iphone16Model | Iphone15Model | Iphone14Model;

export const iphoneTechnicalSpecs = {
  pro: {
    introduced: "2026",
    sourceUrl: "https://www.apple.com/iphone-18-pro/specs/",
    fields: {
      availability: fact("Pre-order from September 12; available September 18, 2026", "Đặt trước từ 12/9; mở bán từ 18/9/2026"),
      finishes: fact("Black, Silver, Glacier, Burgundy; aluminum unibody", "Đen, Bạc, Glacier, Burgundy; thân nhôm nguyên khối"),
      capacity: "256GB / 512GB / 1TB / 2TB",
      dimensions: fact("150.0 × 71.9 × 8.75 mm; 211 g", "150,0 × 71,9 × 8,75 mm; 211 g"),
      display: fact("6.3-inch OLED, 2622×1206 at 460 ppi; ProMotion 120Hz, Always-On, up to 3000 nits outdoors", "OLED 6,3 inch, 2622×1206, 460 ppi; ProMotion 120Hz, Always-On, tối đa 3.000 nit ngoài trời"),
      chip: fact("A20 Pro: 6-core CPU, 7-core GPU, Dual 16-core Neural Engine", "A20 Pro: CPU 6 lõi, GPU 7 lõi, Dual Neural Engine 16 lõi"),
      camera: fact("Three 48MP Fusion cameras; Main with ƒ/1.48–ƒ/4.0 variable aperture; 13–200 mm coverage and up to 8x optical-quality zoom", "Ba camera Fusion 48MP; camera Chính có khẩu độ biến thiên ƒ/1.48–ƒ/4.0; dải 13–200 mm và zoom đến 8x chất lượng quang học"),
      frontCamera: fact("18MP Center Stage; 4K Dolby Vision, Dual Capture, ProRes RAW", "Center Stage 18MP; 4K Dolby Vision, Dual Capture, ProRes RAW"),
      battery: fact("Up to 36 hours video playback; up to 33 hours streamed video", "Phát video đến 36 giờ; phát trực tuyến đến 33 giờ"),
      charging: fact("50% in about 15 minutes by 60W USB-C; MagSafe and Qi2 up to 25W", "50% trong khoảng 15 phút qua USB-C 60W; MagSafe và Qi2 đến 25W"),
      durability: "IP68; Ceramic Shield 2 front and Ceramic Shield back",
      connectivity: "5G, Wi‑Fi 7, Bluetooth 6, Thread, second-generation UWB, Apple C2 modem",
      ports: "USB‑C with USB 3 up to 10Gb/s and DisplayPort",
      authentication: "Face ID",
    },
  },
  duo: {
    introduced: "2026",
    sourceUrl: "https://www.apple.com/iphone-duo/specs/",
    fields: {
      availability: fact("Pre-order from October 16; available October 23, 2026", "Đặt trước từ 16/10; mở bán từ 23/10/2026"),
      finishes: fact("Night Sky or Star White; Grade 5 titanium foldable design", "Night Sky hoặc Star White; thiết kế gập bằng titanium Grade 5"),
      capacity: "256GB / 512GB / 1TB / 2TB",
      dimensions: fact("Open: 164.6 × 117.8 × 5.2 mm; closed: 84.1 × 117.8 × 11.3 mm; 254 g", "Mở: 164,6 × 117,8 × 5,2 mm; gập: 84,1 × 117,8 × 11,3 mm; 254 g"),
      display: fact("7.6-inch inner OLED (1878×2670, 430 ppi) plus 5.4-inch outer OLED (1398×2034, 460 ppi); both ProMotion 120Hz and 3000 nits", "OLED trong 7,6 inch (1878×2670, 430 ppi) và OLED ngoài 5,4 inch (1398×2034, 460 ppi); cả hai ProMotion 120Hz và 3.000 nit"),
      chip: fact("A20 Pro: 6-core CPU, 7-core GPU, Dual 16-core Neural Engine", "A20 Pro: CPU 6 lõi, GPU 7 lõi, Dual Neural Engine 16 lõi"),
      camera: fact("48MP Dual Fusion: Main and Ultra Wide; 0.5x, 1x and optical-quality 2x; Smart Take and Duo Preview", "Dual Fusion 48MP: Chính và Ultra Wide; 0,5x, 1x và 2x chất lượng quang học; Smart Take và Duo Preview"),
      frontCamera: fact("12MP Center Stage outer camera plus under-display inner FaceTime camera", "Camera ngoài Center Stage 12MP và camera FaceTime ẩn dưới màn hình trong"),
      battery: fact("Typical use up to 24 hours; video up to 44 hours on outer or 31 hours on inner display", "Dùng thông thường đến 24 giờ; phát video đến 44 giờ trên màn hình ngoài hoặc 31 giờ trên màn hình trong"),
      charging: fact("50% in about 20 minutes by 60W USB-C; MagSafe and Qi2 up to 25W", "50% trong khoảng 20 phút qua USB-C 60W; MagSafe và Qi2 đến 25W"),
      durability: "IP68; Ceramic Shield 2 front and Ceramic Shield back",
      connectivity: "5G, Wi‑Fi 7, Bluetooth 6, Thread, second-generation UWB, Apple C2 modem",
      ports: "USB‑C with USB 3 up to 10Gb/s and DisplayPort",
      authentication: "Touch ID in the side button",
      accessories: "Apple Pencil (USB‑C)",
    },
  },
  "17-pro": {
    introduced: "2025",
    sourceUrl: "https://support.apple.com/en-us/125090",
    fields: {
      finishes: fact("Silver, Cosmic Orange, Deep Blue; aluminum unibody", "Bạc, Cosmic Orange, Deep Blue; thân nhôm nguyên khối"),
      capacity: "256GB / 512GB / 1TB",
      dimensions: fact("150.0 × 71.9 × 8.75 mm; 206 g", "150,0 × 71,9 × 8,75 mm; 206 g"),
      display: fact("6.3-inch OLED, 2622×1206 at 460 ppi; ProMotion 120Hz, Always-On, up to 3000 nits outdoors", "OLED 6,3 inch, 2622×1206, 460 ppi; ProMotion 120Hz, Always-On, tối đa 3.000 nit ngoài trời"),
      chip: fact("A19 Pro: 6-core CPU, 6-core GPU with Neural Accelerators, 16-core Neural Engine", "A19 Pro: CPU 6 lõi, GPU 6 lõi có Neural Accelerator, Neural Engine 16 lõi"),
      camera: fact("Three 48MP Fusion cameras; 13–200 mm coverage, 4x optical and up to 8x optical-quality Telephoto", "Ba camera Fusion 48MP; dải 13–200 mm, tele quang học 4x và đến 8x chất lượng quang học"),
      frontCamera: "18MP Center Stage; 4K Dolby Vision",
      battery: fact("Up to 33 hours video playback", "Phát video đến 33 giờ"),
      charging: fact("50% in about 20 minutes by 40W USB‑C; MagSafe and Qi2 up to 25W", "50% trong khoảng 20 phút qua USB‑C 40W; MagSafe và Qi2 đến 25W"),
      durability: "IP68; Ceramic Shield 2 front and Ceramic Shield back",
      connectivity: "5G, Wi‑Fi 7, Bluetooth 6, Thread, second-generation UWB",
      ports: "USB‑C with USB 3 up to 10Gb/s and DisplayPort",
      authentication: "Face ID",
    },
  },
  "17-pro-max": {
    introduced: "2025",
    sourceUrl: "https://support.apple.com/en-us/125091",
    fields: {
      finishes: fact("Silver, Cosmic Orange, Deep Blue; aluminum unibody", "Bạc, Cosmic Orange, Deep Blue; thân nhôm nguyên khối"),
      capacity: "256GB / 512GB / 1TB / 2TB",
      dimensions: fact("163.4 × 78.0 × 8.75 mm; 233 g", "163,4 × 78,0 × 8,75 mm; 233 g"),
      display: fact("6.9-inch OLED, 2868×1320 at 460 ppi; ProMotion 120Hz, Always-On, up to 3000 nits outdoors", "OLED 6,9 inch, 2868×1320, 460 ppi; ProMotion 120Hz, Always-On, tối đa 3.000 nit ngoài trời"),
      chip: fact("A19 Pro: 6-core CPU, 6-core GPU with Neural Accelerators, 16-core Neural Engine", "A19 Pro: CPU 6 lõi, GPU 6 lõi có Neural Accelerator, Neural Engine 16 lõi"),
      camera: fact("Three 48MP Fusion cameras; 13–200 mm coverage, 4x optical and up to 8x optical-quality Telephoto", "Ba camera Fusion 48MP; dải 13–200 mm, tele quang học 4x và đến 8x chất lượng quang học"),
      frontCamera: "18MP Center Stage; 4K Dolby Vision",
      battery: fact("Up to 39 hours video playback", "Phát video đến 39 giờ"),
      charging: fact("50% in about 20 minutes by 40W USB‑C; MagSafe and Qi2 up to 25W", "50% trong khoảng 20 phút qua USB‑C 40W; MagSafe và Qi2 đến 25W"),
      durability: "IP68; Ceramic Shield 2 front and Ceramic Shield back",
      connectivity: "5G, Wi‑Fi 7, Bluetooth 6, Thread, second-generation UWB",
      ports: "USB‑C with USB 3 up to 10Gb/s and DisplayPort",
      authentication: "Face ID",
    },
  },
  air: {
    introduced: "2025",
    sourceUrl: "https://www.apple.com/iphone-air/specs/",
    fields: {
      finishes: fact("Space Black, Cloud White, Light Gold, Sky Blue; titanium", "Space Black, Cloud White, Light Gold, Sky Blue; titanium"),
      capacity: "256GB / 512GB / 1TB",
      dimensions: fact("156.2 × 74.7 × 5.64 mm; 165 g", "156,2 × 74,7 × 5,64 mm; 165 g"),
      display: fact("6.5-inch OLED, 2736×1260 at 460 ppi; ProMotion 120Hz, Always-On, up to 3000 nits outdoors", "OLED 6,5 inch, 2736×1260, 460 ppi; ProMotion 120Hz, Always-On, tối đa 3.000 nit ngoài trời"),
      chip: fact("A19 Pro: 6-core CPU, 5-core GPU, 16-core Neural Engine", "A19 Pro: CPU 6 lõi, GPU 5 lõi, Neural Engine 16 lõi"),
      camera: fact("48MP Fusion Main with optical-quality 2x Telephoto; up to 10x digital zoom", "Camera Chính Fusion 48MP có tele 2x chất lượng quang học; zoom số đến 10x"),
      frontCamera: "18MP Center Stage; 4K Dolby Vision and Dual Capture",
      battery: fact("Up to 27 hours video playback; up to 40 hours with iPhone Air MagSafe Battery", "Phát video đến 27 giờ; đến 40 giờ khi gắn iPhone Air MagSafe Battery"),
      charging: "USB‑C fast charge; MagSafe and Qi2 up to 20W",
      durability: "IP68; Ceramic Shield 2 front and Ceramic Shield back",
      connectivity: "5G sub‑6GHz, Wi‑Fi 7, Bluetooth 6, Thread, second-generation UWB; Apple C1X modem",
      ports: "USB‑C with USB 2 up to 480Mb/s",
      authentication: "Face ID",
    },
  },
  "17": {
    introduced: "2025",
    sourceUrl: "https://www.apple.com/iphone-17/specs/",
    fields: {
      finishes: fact("Black, White, Mist Blue, Sage, Lavender; aluminum", "Đen, Trắng, Mist Blue, Sage, Lavender; nhôm"),
      capacity: "256GB / 512GB",
      dimensions: fact("149.6 × 71.5 × 7.95 mm; 177 g", "149,6 × 71,5 × 7,95 mm; 177 g"),
      display: fact("6.3-inch OLED, 2622×1206 at 460 ppi; ProMotion 120Hz, Always-On, up to 3000 nits outdoors", "OLED 6,3 inch, 2622×1206, 460 ppi; ProMotion 120Hz, Always-On, tối đa 3.000 nit ngoài trời"),
      chip: fact("A19: 6-core CPU, 5-core GPU with Neural Accelerators, 16-core Neural Engine", "A19: CPU 6 lõi, GPU 5 lõi có Neural Accelerator, Neural Engine 16 lõi"),
      camera: fact("48MP Dual Fusion: Main with optical-quality 2x plus 48MP Ultra Wide with macro", "Dual Fusion 48MP: camera Chính có 2x chất lượng quang học và Ultra Wide 48MP hỗ trợ macro"),
      frontCamera: "18MP Center Stage; 4K Dolby Vision and Dual Capture",
      battery: fact("Up to 30 hours video playback; up to 27 hours streamed", "Phát video đến 30 giờ; phát trực tuyến đến 27 giờ"),
      charging: fact("50% in 20 minutes by 40W USB‑C; MagSafe and Qi2 up to 25W", "50% trong 20 phút qua USB‑C 40W; MagSafe và Qi2 đến 25W"),
      durability: "IP68; Ceramic Shield 2 front",
      connectivity: "5G, Wi‑Fi 7, Bluetooth 6, Thread, second-generation UWB",
      ports: "USB‑C with USB 2 up to 480Mb/s and DisplayPort",
      authentication: "Face ID",
    },
  },
  "17e": {
    introduced: "2026",
    sourceUrl: "https://www.apple.com/iphone-17e/specs/",
    fields: {
      finishes: fact("Black, White, Soft Pink; aluminum", "Đen, Trắng, Soft Pink; nhôm"),
      capacity: "256GB / 512GB",
      dimensions: fact("146.7 × 71.5 × 7.80 mm; 169 g", "146,7 × 71,5 × 7,80 mm; 169 g"),
      display: fact("6.1-inch OLED, 2532×1170 at 460 ppi; 800 nits typical, 1200 nits HDR", "OLED 6,1 inch, 2532×1170, 460 ppi; 800 nit tiêu chuẩn, 1.200 nit HDR"),
      chip: fact("A19: 6-core CPU, 4-core GPU with Neural Accelerators, 16-core Neural Engine", "A19: CPU 6 lõi, GPU 4 lõi có Neural Accelerator, Neural Engine 16 lõi"),
      camera: fact("48MP Fusion Main with optical-quality 2x Telephoto; up to 10x digital zoom", "Camera Chính Fusion 48MP có tele 2x chất lượng quang học; zoom số đến 10x"),
      frontCamera: "12MP TrueDepth; 4K Dolby Vision",
      battery: fact("Up to 26 hours video playback; up to 21 hours streamed", "Phát video đến 26 giờ; phát trực tuyến đến 21 giờ"),
      charging: fact("50% in 30 minutes by 20W USB‑C; MagSafe and Qi2 up to 15W", "50% trong 30 phút qua USB‑C 20W; MagSafe và Qi2 đến 15W"),
      durability: "IP68; Ceramic Shield 2 front",
      connectivity: "5G sub‑6GHz, Wi‑Fi 6, Bluetooth 5.3; Apple C1X modem",
      ports: "USB‑C with USB 2 up to 480Mb/s",
      authentication: "Face ID",
    },
  },
  "16-pro": {
    introduced: "2024",
    sourceUrl: "https://support.apple.com/en-us/121031",
    fields: {
      finishes: fact("Black, White, Natural, or Desert Titanium", "Titanium Đen, Trắng, Tự Nhiên hoặc Sa Mạc"),
      capacity: "128GB / 256GB / 512GB / 1TB",
      dimensions: fact("149.6 × 71.5 × 8.25 mm; 199 g", "149,6 × 71,5 × 8,25 mm; 199 g"),
      display: fact("6.3-inch OLED, 2622×1206 at 460 ppi; ProMotion 120Hz, Always-On, up to 2000 nits outdoors", "OLED 6,3 inch, 2622×1206, 460 ppi; ProMotion 120Hz, Always-On, tối đa 2.000 nit ngoài trời"),
      chip: fact("A18 Pro: 6-core CPU, 6-core GPU, 16-core Neural Engine", "A18 Pro: CPU 6 lõi, GPU 6 lõi, Neural Engine 16 lõi"),
      camera: fact("48MP Fusion Main, 48MP Ultra Wide, 12MP 5x Telephoto; LiDAR; up to 25x digital zoom", "Chính Fusion 48MP, Ultra Wide 48MP, Tele 5x 12MP; LiDAR; zoom số đến 25x"),
      frontCamera: "12MP TrueDepth; 4K Dolby Vision",
      battery: fact("Up to 27 hours video playback", "Phát video đến 27 giờ"),
      charging: fact("50% in about 30 minutes by 20W USB‑C; MagSafe and Qi2 up to 25W", "50% trong khoảng 30 phút qua USB‑C 20W; MagSafe và Qi2 đến 25W"),
      durability: "IP68; Grade 5 titanium and Ceramic Shield front",
      connectivity: "5G, Wi‑Fi 7, Bluetooth 5.3, Thread, second-generation UWB",
      ports: "USB‑C with USB 3 up to 10Gb/s and DisplayPort",
      authentication: "Face ID",
    },
  },
  "16-pro-max": {
    introduced: "2024",
    sourceUrl: "https://support.apple.com/en-us/121032",
    fields: {
      finishes: fact("Black, White, Natural, or Desert Titanium", "Titanium Đen, Trắng, Tự Nhiên hoặc Sa Mạc"),
      capacity: "256GB / 512GB / 1TB",
      dimensions: fact("163.0 × 77.6 × 8.25 mm; 227 g", "163,0 × 77,6 × 8,25 mm; 227 g"),
      display: fact("6.9-inch OLED, 2868×1320 at 460 ppi; ProMotion 120Hz, Always-On, up to 2000 nits outdoors", "OLED 6,9 inch, 2868×1320, 460 ppi; ProMotion 120Hz, Always-On, tối đa 2.000 nit ngoài trời"),
      chip: fact("A18 Pro: 6-core CPU, 6-core GPU, 16-core Neural Engine", "A18 Pro: CPU 6 lõi, GPU 6 lõi, Neural Engine 16 lõi"),
      camera: fact("48MP Fusion Main, 48MP Ultra Wide, 12MP 5x Telephoto; LiDAR; up to 25x digital zoom", "Chính Fusion 48MP, Ultra Wide 48MP, Tele 5x 12MP; LiDAR; zoom số đến 25x"),
      frontCamera: "12MP TrueDepth; 4K Dolby Vision",
      battery: fact("Up to 33 hours video playback", "Phát video đến 33 giờ"),
      charging: fact("50% in about 30 minutes by 20W USB‑C; MagSafe and Qi2 up to 25W", "50% trong khoảng 30 phút qua USB‑C 20W; MagSafe và Qi2 đến 25W"),
      durability: "IP68; Grade 5 titanium and Ceramic Shield front",
      connectivity: "5G, Wi‑Fi 7, Bluetooth 5.3, Thread, second-generation UWB",
      ports: "USB‑C with USB 3 up to 10Gb/s and DisplayPort",
      authentication: "Face ID",
    },
  },
  "16": {
    introduced: "2024",
    sourceUrl: "https://www.apple.com/iphone-16/specs/",
    fields: {
      finishes: fact("Black, White, Pink, Teal, Ultramarine; aluminum", "Đen, Trắng, Hồng, Xanh Mòng Két, Xanh Lưu Ly; nhôm"),
      capacity: "128GB / 256GB / 512GB",
      dimensions: fact("147.6 × 71.6 × 7.80 mm; 170 g", "147,6 × 71,6 × 7,80 mm; 170 g"),
      display: fact("6.1-inch OLED, 2556×1179 at 460 ppi; up to 2000 nits outdoors", "OLED 6,1 inch, 2556×1179, 460 ppi; tối đa 2.000 nit ngoài trời"),
      chip: fact("A18: 6-core CPU, 5-core GPU, 16-core Neural Engine", "A18: CPU 6 lõi, GPU 5 lõi, Neural Engine 16 lõi"),
      camera: fact("48MP Fusion Main with optical-quality 2x plus 12MP Ultra Wide with macro", "Camera Chính Fusion 48MP có 2x chất lượng quang học và Ultra Wide 12MP hỗ trợ macro"),
      frontCamera: "12MP TrueDepth; 4K Dolby Vision",
      battery: fact("Up to 22 hours video playback", "Phát video đến 22 giờ"),
      charging: fact("50% in about 30 minutes by 20W USB‑C; MagSafe and Qi2 up to 25W", "50% trong khoảng 30 phút qua USB‑C 20W; MagSafe và Qi2 đến 25W"),
      durability: "IP68; Ceramic Shield front",
      connectivity: "5G, Wi‑Fi 7, Bluetooth 5.3, Thread, second-generation UWB",
      ports: "USB‑C with USB 2 up to 480Mb/s and DisplayPort",
      authentication: "Face ID",
    },
  },
  "16-plus": {
    introduced: "2024",
    sourceUrl: "https://www.apple.com/iphone-16/specs/",
    fields: {
      finishes: fact("Black, White, Pink, Teal, Ultramarine; aluminum", "Đen, Trắng, Hồng, Xanh Mòng Két, Xanh Lưu Ly; nhôm"),
      capacity: "128GB / 256GB / 512GB",
      dimensions: fact("160.9 × 77.8 × 7.80 mm; 199 g", "160,9 × 77,8 × 7,80 mm; 199 g"),
      display: fact("6.7-inch OLED, 2796×1290 at 460 ppi; up to 2000 nits outdoors", "OLED 6,7 inch, 2796×1290, 460 ppi; tối đa 2.000 nit ngoài trời"),
      chip: fact("A18: 6-core CPU, 5-core GPU, 16-core Neural Engine", "A18: CPU 6 lõi, GPU 5 lõi, Neural Engine 16 lõi"),
      camera: fact("48MP Fusion Main with optical-quality 2x plus 12MP Ultra Wide with macro", "Camera Chính Fusion 48MP có 2x chất lượng quang học và Ultra Wide 12MP hỗ trợ macro"),
      frontCamera: "12MP TrueDepth; 4K Dolby Vision",
      battery: fact("Up to 27 hours video playback", "Phát video đến 27 giờ"),
      charging: fact("50% in about 30 minutes by 20W USB‑C; MagSafe and Qi2 up to 25W", "50% trong khoảng 30 phút qua USB‑C 20W; MagSafe và Qi2 đến 25W"),
      durability: "IP68; Ceramic Shield front",
      connectivity: "5G, Wi‑Fi 7, Bluetooth 5.3, Thread, second-generation UWB",
      ports: "USB‑C with USB 2 up to 480Mb/s and DisplayPort",
      authentication: "Face ID",
    },
  },
  "16e": {
    introduced: "2025",
    sourceUrl: "https://support.apple.com/en-us/122208",
    fields: {
      finishes: fact("Black or White; aluminum", "Đen hoặc Trắng; nhôm"),
      capacity: "128GB / 256GB / 512GB",
      dimensions: fact("146.7 × 71.5 × 7.80 mm; 167 g", "146,7 × 71,5 × 7,80 mm; 167 g"),
      display: fact("6.1-inch OLED, 2532×1170 at 460 ppi; 800 nits typical, 1200 nits HDR", "OLED 6,1 inch, 2532×1170, 460 ppi; 800 nit tiêu chuẩn, 1.200 nit HDR"),
      chip: fact("A18: 6-core CPU, 4-core GPU, 16-core Neural Engine", "A18: CPU 6 lõi, GPU 4 lõi, Neural Engine 16 lõi"),
      camera: fact("48MP Fusion Main with optical-quality 2x Telephoto", "Camera Chính Fusion 48MP có tele 2x chất lượng quang học"),
      frontCamera: "12MP TrueDepth; 4K Dolby Vision",
      battery: fact("Up to 26 hours video playback", "Phát video đến 26 giờ"),
      charging: fact("USB‑C fast charge; Qi wireless charging up to 7.5W; no MagSafe", "Sạc nhanh USB‑C; sạc không dây Qi đến 7,5W; không có MagSafe"),
      durability: "IP68; Ceramic Shield front",
      connectivity: "5G sub‑6GHz, Wi‑Fi 6, Bluetooth 5.3; Apple C1 modem",
      ports: "USB‑C with USB 2 up to 480Mb/s",
      authentication: "Face ID",
    },
  },
  "15-pro": {
    introduced: "2023",
    sourceUrl: "https://support.apple.com/en-us/111829",
    fields: {
      finishes: fact("Black, White, Blue, or Natural Titanium", "Titanium Đen, Trắng, Xanh hoặc Tự Nhiên"),
      capacity: "128GB / 256GB / 512GB / 1TB",
      dimensions: fact("146.6 × 70.6 × 8.25 mm; 187 g", "146,6 × 70,6 × 8,25 mm; 187 g"),
      display: fact("6.1-inch OLED, 2556×1179 at 460 ppi; ProMotion 120Hz, Always-On, up to 2000 nits outdoors", "OLED 6,1 inch, 2556×1179, 460 ppi; ProMotion 120Hz, Always-On, tối đa 2.000 nit ngoài trời"),
      chip: fact("A17 Pro: 6-core CPU, 6-core GPU, 16-core Neural Engine", "A17 Pro: CPU 6 lõi, GPU 6 lõi, Neural Engine 16 lõi"),
      camera: fact("48MP Main, 12MP Ultra Wide, 12MP 3x Telephoto; LiDAR", "Chính 48MP, Ultra Wide 12MP, Tele 3x 12MP; LiDAR"),
      frontCamera: "12MP TrueDepth; 4K Dolby Vision",
      battery: fact("Up to 23 hours video playback", "Phát video đến 23 giờ"),
      charging: fact("50% in about 30 minutes by 20W USB‑C; MagSafe and Qi2 up to 15W", "50% trong khoảng 30 phút qua USB‑C 20W; MagSafe và Qi2 đến 15W"),
      durability: "IP68; Grade 5 titanium and Ceramic Shield front",
      connectivity: "5G, Wi‑Fi 6E, Bluetooth 5.3, Thread, second-generation UWB",
      ports: "USB‑C with USB 3 up to 10Gb/s and DisplayPort",
      authentication: "Face ID",
    },
  },
  "15-pro-max": {
    introduced: "2023",
    sourceUrl: "https://support.apple.com/en-us/111828",
    fields: {
      finishes: fact("Black, White, Blue, or Natural Titanium", "Titanium Đen, Trắng, Xanh hoặc Tự Nhiên"),
      capacity: "256GB / 512GB / 1TB",
      dimensions: fact("159.9 × 76.7 × 8.25 mm; 221 g", "159,9 × 76,7 × 8,25 mm; 221 g"),
      display: fact("6.7-inch OLED, 2796×1290 at 460 ppi; ProMotion 120Hz, Always-On, up to 2000 nits outdoors", "OLED 6,7 inch, 2796×1290, 460 ppi; ProMotion 120Hz, Always-On, tối đa 2.000 nit ngoài trời"),
      chip: fact("A17 Pro: 6-core CPU, 6-core GPU, 16-core Neural Engine", "A17 Pro: CPU 6 lõi, GPU 6 lõi, Neural Engine 16 lõi"),
      camera: fact("48MP Main, 12MP Ultra Wide, 12MP 5x Telephoto; LiDAR", "Chính 48MP, Ultra Wide 12MP, Tele 5x 12MP; LiDAR"),
      frontCamera: "12MP TrueDepth; 4K Dolby Vision",
      battery: fact("Up to 29 hours video playback", "Phát video đến 29 giờ"),
      charging: fact("50% in about 30 minutes by 20W USB‑C; MagSafe and Qi2 up to 15W", "50% trong khoảng 30 phút qua USB‑C 20W; MagSafe và Qi2 đến 15W"),
      durability: "IP68; Grade 5 titanium and Ceramic Shield front",
      connectivity: "5G, Wi‑Fi 6E, Bluetooth 5.3, Thread, second-generation UWB",
      ports: "USB‑C with USB 3 up to 10Gb/s and DisplayPort",
      authentication: "Face ID",
    },
  },
  "15": {
    introduced: "2023",
    sourceUrl: "https://support.apple.com/en-us/111831",
    fields: {
      finishes: fact("Black, Blue, Green, Yellow, Pink; aluminum", "Đen, Xanh Dương, Xanh Lá, Vàng, Hồng; nhôm"),
      capacity: "128GB / 256GB / 512GB",
      dimensions: fact("147.6 × 71.6 × 7.80 mm; 171 g", "147,6 × 71,6 × 7,80 mm; 171 g"),
      display: fact("6.1-inch OLED, 2556×1179 at 460 ppi; up to 2000 nits outdoors", "OLED 6,1 inch, 2556×1179, 460 ppi; tối đa 2.000 nit ngoài trời"),
      chip: fact("A16 Bionic: 6-core CPU, 5-core GPU, 16-core Neural Engine", "A16 Bionic: CPU 6 lõi, GPU 5 lõi, Neural Engine 16 lõi"),
      camera: fact("48MP Main with optical-quality 2x plus 12MP Ultra Wide", "Camera Chính 48MP có 2x chất lượng quang học và Ultra Wide 12MP"),
      frontCamera: "12MP TrueDepth; 4K Dolby Vision",
      battery: fact("Up to 20 hours video playback", "Phát video đến 20 giờ"),
      charging: fact("50% in about 30 minutes by 20W USB‑C; MagSafe and Qi2 up to 15W", "50% trong khoảng 30 phút qua USB‑C 20W; MagSafe và Qi2 đến 15W"),
      durability: "IP68; Ceramic Shield front",
      connectivity: "5G, Wi‑Fi 6, Bluetooth 5.3, second-generation UWB",
      ports: "USB‑C with USB 2 up to 480Mb/s and DisplayPort",
      authentication: "Face ID",
    },
  },
  "15-plus": {
    introduced: "2023",
    sourceUrl: "https://support.apple.com/en-us/111830",
    fields: {
      finishes: fact("Black, Blue, Green, Yellow, Pink; aluminum", "Đen, Xanh Dương, Xanh Lá, Vàng, Hồng; nhôm"),
      capacity: "128GB / 256GB / 512GB",
      dimensions: fact("160.9 × 77.8 × 7.80 mm; 201 g", "160,9 × 77,8 × 7,80 mm; 201 g"),
      display: fact("6.7-inch OLED, 2796×1290 at 460 ppi; up to 2000 nits outdoors", "OLED 6,7 inch, 2796×1290, 460 ppi; tối đa 2.000 nit ngoài trời"),
      chip: fact("A16 Bionic: 6-core CPU, 5-core GPU, 16-core Neural Engine", "A16 Bionic: CPU 6 lõi, GPU 5 lõi, Neural Engine 16 lõi"),
      camera: fact("48MP Main with optical-quality 2x plus 12MP Ultra Wide", "Camera Chính 48MP có 2x chất lượng quang học và Ultra Wide 12MP"),
      frontCamera: "12MP TrueDepth; 4K Dolby Vision",
      battery: fact("Up to 26 hours video playback", "Phát video đến 26 giờ"),
      charging: fact("50% in about 30 minutes by 20W USB‑C; MagSafe and Qi2 up to 15W", "50% trong khoảng 30 phút qua USB‑C 20W; MagSafe và Qi2 đến 15W"),
      durability: "IP68; Ceramic Shield front",
      connectivity: "5G, Wi‑Fi 6, Bluetooth 5.3, second-generation UWB",
      ports: "USB‑C with USB 2 up to 480Mb/s and DisplayPort",
      authentication: "Face ID",
    },
  },
  "14-pro": {
    introduced: "2022",
    sourceUrl: "https://support.apple.com/en-us/111849",
    fields: {
      finishes: fact("Space Black, Silver, Gold, Deep Purple; stainless steel with textured matte glass", "Đen Không Gian, Bạc, Vàng, Tím Đậm; thép không gỉ và kính nhám"),
      capacity: "128GB / 256GB / 512GB / 1TB",
      dimensions: fact("147.5 × 71.5 × 7.85 mm; 206 g", "147,5 × 71,5 × 7,85 mm; 206 g"),
      display: fact("6.1-inch OLED, 2556×1179 at 460 ppi; Dynamic Island, Always-On, ProMotion up to 120Hz; 1000 nits typical, 1600 nits HDR, 2000 nits outdoors", "OLED 6,1 inch, 2556×1179, 460 ppi; Dynamic Island, Luôn Bật, ProMotion đến 120Hz; 1.000 nit tiêu chuẩn, 1.600 nit HDR, 2.000 nit ngoài trời"),
      chip: fact("A16 Bionic: 6-core CPU, 5-core GPU, 16-core Neural Engine", "A16 Bionic: CPU 6 lõi, GPU 5 lõi, Neural Engine 16 lõi"),
      camera: fact("48MP Main, 12MP Ultra Wide, 12MP 3x Telephoto; optical-quality 2x; LiDAR; 6x optical zoom range and up to 15x digital zoom", "Chính 48MP, Ultra Wide 12MP, Tele 3x 12MP; 2x chất lượng quang học; LiDAR; dải zoom quang học 6x và zoom số đến 15x"),
      frontCamera: fact("12MP TrueDepth, ƒ/1.9 with autofocus; 4K Dolby Vision up to 60 fps", "TrueDepth 12MP, ƒ/1.9, lấy nét tự động; 4K Dolby Vision đến 60 fps"),
      battery: fact("Up to 23 hours video, 20 hours streamed video, or 75 hours audio playback", "Phát video đến 23 giờ, video trực tuyến 20 giờ hoặc âm thanh 75 giờ"),
      charging: fact("50% in about 30 minutes with a 20W adapter; MagSafe up to 15W and Qi up to 7.5W", "50% trong khoảng 30 phút với bộ tiếp hợp 20W; MagSafe đến 15W và Qi đến 7,5W"),
      durability: fact("IP68 to 6 m for 30 minutes; Ceramic Shield front", "IP68 ở độ sâu 6 m trong 30 phút; mặt trước Ceramic Shield"),
      connectivity: "5G, Gigabit LTE, Wi‑Fi 6, Bluetooth 5.3, Ultra Wideband, NFC",
      ports: fact("Lightning; video output up to 1080p through compatible adapters", "Lightning; xuất hình ảnh đến 1080p qua bộ chuyển đổi tương thích"),
      authentication: "Face ID",
    },
  },
  "14-pro-max": {
    introduced: "2022",
    sourceUrl: "https://support.apple.com/en-us/111846",
    fields: {
      finishes: fact("Space Black, Silver, Gold, Deep Purple; stainless steel with textured matte glass", "Đen Không Gian, Bạc, Vàng, Tím Đậm; thép không gỉ và kính nhám"),
      capacity: "128GB / 256GB / 512GB / 1TB",
      dimensions: fact("160.7 × 77.6 × 7.85 mm; 240 g", "160,7 × 77,6 × 7,85 mm; 240 g"),
      display: fact("6.7-inch OLED, 2796×1290 at 460 ppi; Dynamic Island, Always-On, ProMotion up to 120Hz; 1000 nits typical, 1600 nits HDR, 2000 nits outdoors", "OLED 6,7 inch, 2796×1290, 460 ppi; Dynamic Island, Luôn Bật, ProMotion đến 120Hz; 1.000 nit tiêu chuẩn, 1.600 nit HDR, 2.000 nit ngoài trời"),
      chip: fact("A16 Bionic: 6-core CPU, 5-core GPU, 16-core Neural Engine", "A16 Bionic: CPU 6 lõi, GPU 5 lõi, Neural Engine 16 lõi"),
      camera: fact("48MP Main, 12MP Ultra Wide, 12MP 3x Telephoto; optical-quality 2x; LiDAR; 6x optical zoom range and up to 15x digital zoom", "Chính 48MP, Ultra Wide 12MP, Tele 3x 12MP; 2x chất lượng quang học; LiDAR; dải zoom quang học 6x và zoom số đến 15x"),
      frontCamera: fact("12MP TrueDepth, ƒ/1.9 with autofocus; 4K Dolby Vision up to 60 fps", "TrueDepth 12MP, ƒ/1.9, lấy nét tự động; 4K Dolby Vision đến 60 fps"),
      battery: fact("Up to 29 hours video, 25 hours streamed video, or 95 hours audio playback", "Phát video đến 29 giờ, video trực tuyến 25 giờ hoặc âm thanh 95 giờ"),
      charging: fact("50% in about 35 minutes with a 20W adapter; MagSafe up to 15W and Qi up to 7.5W", "50% trong khoảng 35 phút với bộ tiếp hợp 20W; MagSafe đến 15W và Qi đến 7,5W"),
      durability: fact("IP68 to 6 m for 30 minutes; Ceramic Shield front", "IP68 ở độ sâu 6 m trong 30 phút; mặt trước Ceramic Shield"),
      connectivity: "5G, Gigabit LTE, Wi‑Fi 6, Bluetooth 5.3, Ultra Wideband, NFC",
      ports: fact("Lightning; video output up to 1080p through compatible adapters", "Lightning; xuất hình ảnh đến 1080p qua bộ chuyển đổi tương thích"),
      authentication: "Face ID",
    },
  },
  "14": {
    introduced: "2022",
    sourceUrl: "https://support.apple.com/en-us/111850",
    fields: {
      finishes: fact("Midnight, Purple, Starlight, (PRODUCT)RED, Blue, Yellow; aluminum with glass back", "Màu Đêm, Tím, Ánh Sao, (PRODUCT)RED, Xanh Dương, Vàng; nhôm và mặt lưng kính"),
      capacity: "128GB / 256GB / 512GB",
      dimensions: fact("146.7 × 71.5 × 7.80 mm; 172 g", "146,7 × 71,5 × 7,80 mm; 172 g"),
      display: fact("6.1-inch OLED, 2532×1170 at 460 ppi; 800 nits typical and 1200 nits HDR", "OLED 6,1 inch, 2532×1170, 460 ppi; 800 nit tiêu chuẩn và 1.200 nit HDR"),
      chip: fact("A15 Bionic: 6-core CPU, 5-core GPU, 16-core Neural Engine", "A15 Bionic: CPU 6 lõi, GPU 5 lõi, Neural Engine 16 lõi"),
      camera: fact("Dual 12MP system: Main ƒ/1.5 with sensor-shift OIS and 12MP Ultra Wide; 2x optical zoom out and up to 5x digital zoom", "Hệ thống kép 12MP: camera Chính ƒ/1.5 với OIS dịch chuyển cảm biến và Ultra Wide 12MP; zoom quang học thu nhỏ 2x và zoom số đến 5x"),
      frontCamera: fact("12MP TrueDepth, ƒ/1.9 with autofocus; 4K Dolby Vision up to 60 fps", "TrueDepth 12MP, ƒ/1.9, lấy nét tự động; 4K Dolby Vision đến 60 fps"),
      battery: fact("Up to 20 hours video, 16 hours streamed video, or 80 hours audio playback", "Phát video đến 20 giờ, video trực tuyến 16 giờ hoặc âm thanh 80 giờ"),
      charging: fact("50% in about 30 minutes with a 20W adapter; MagSafe up to 15W and Qi up to 7.5W", "50% trong khoảng 30 phút với bộ tiếp hợp 20W; MagSafe đến 15W và Qi đến 7,5W"),
      durability: fact("IP68 to 6 m for 30 minutes; Ceramic Shield front", "IP68 ở độ sâu 6 m trong 30 phút; mặt trước Ceramic Shield"),
      connectivity: "5G, Gigabit LTE, Wi‑Fi 6, Bluetooth 5.3, Ultra Wideband, NFC",
      ports: fact("Lightning; video output up to 1080p through compatible adapters", "Lightning; xuất hình ảnh đến 1080p qua bộ chuyển đổi tương thích"),
      authentication: "Face ID",
    },
  },
  "14-plus": {
    introduced: "2022",
    sourceUrl: "https://support.apple.com/en-us/111854",
    fields: {
      finishes: fact("Midnight, Purple, Starlight, (PRODUCT)RED, Blue, Yellow; aluminum with glass back", "Màu Đêm, Tím, Ánh Sao, (PRODUCT)RED, Xanh Dương, Vàng; nhôm và mặt lưng kính"),
      capacity: "128GB / 256GB / 512GB",
      dimensions: fact("160.8 × 78.1 × 7.80 mm; 203 g", "160,8 × 78,1 × 7,80 mm; 203 g"),
      display: fact("6.7-inch OLED, 2778×1284 at 458 ppi; 800 nits typical and 1200 nits HDR", "OLED 6,7 inch, 2778×1284, 458 ppi; 800 nit tiêu chuẩn và 1.200 nit HDR"),
      chip: fact("A15 Bionic: 6-core CPU, 5-core GPU, 16-core Neural Engine", "A15 Bionic: CPU 6 lõi, GPU 5 lõi, Neural Engine 16 lõi"),
      camera: fact("Dual 12MP system: Main ƒ/1.5 with sensor-shift OIS and 12MP Ultra Wide; 2x optical zoom out and up to 5x digital zoom", "Hệ thống kép 12MP: camera Chính ƒ/1.5 với OIS dịch chuyển cảm biến và Ultra Wide 12MP; zoom quang học thu nhỏ 2x và zoom số đến 5x"),
      frontCamera: fact("12MP TrueDepth, ƒ/1.9 with autofocus; 4K Dolby Vision up to 60 fps", "TrueDepth 12MP, ƒ/1.9, lấy nét tự động; 4K Dolby Vision đến 60 fps"),
      battery: fact("Up to 26 hours video, 20 hours streamed video, or 100 hours audio playback", "Phát video đến 26 giờ, video trực tuyến 20 giờ hoặc âm thanh 100 giờ"),
      charging: fact("50% in about 30 minutes with a 20W adapter; MagSafe up to 15W and Qi up to 7.5W", "50% trong khoảng 30 phút với bộ tiếp hợp 20W; MagSafe đến 15W và Qi đến 7,5W"),
      durability: fact("IP68 to 6 m for 30 minutes; Ceramic Shield front", "IP68 ở độ sâu 6 m trong 30 phút; mặt trước Ceramic Shield"),
      connectivity: "5G, Gigabit LTE, Wi‑Fi 6, Bluetooth 5.3, Ultra Wideband, NFC",
      ports: fact("Lightning; video output up to 1080p through compatible adapters", "Lightning; xuất hình ảnh đến 1080p qua bộ chuyển đổi tương thích"),
      authentication: "Face ID",
    },
  },
} as const satisfies Pick<ProductTechnicalSpecCatalog, IphoneModel>;
