import type { MacModel } from "../product-data";
import { fact, type ProductTechnicalSpecCatalog } from "./types";

export const macTechnicalSpecs = {
  "macbook-air-m5": {
    introduced: "2026",
    sourceUrl: "https://www.apple.com/macbook-air/specs/",
    fields: {
      finishes: fact("Sky Blue, Silver, Starlight, Midnight", "Xanh Da Trời, Bạc, Ánh Sao, Đêm Xanh Thẳm"),
      capacity: "512GB / 1TB / 2TB / 4TB SSD",
      dimensions: fact("13-inch: 30.41 × 21.5 × 1.13 cm, 1.23 kg; 15-inch: 34.04 × 23.76 × 1.15 cm, 1.51 kg", "13 inch: 30,41 × 21,5 × 1,13 cm, 1,23 kg; 15 inch: 34,04 × 23,76 × 1,15 cm, 1,51 kg"),
      display: fact("13.6-inch 2560×1664 or 15.3-inch 2880×1864 Liquid Retina; 224 ppi, P3, True Tone, 500 nits", "Liquid Retina 13,6 inch 2560×1664 hoặc 15,3 inch 2880×1864; 224 ppi, P3, True Tone, 500 nit"),
      chip: fact("M5: 10-core CPU, 8- or 10-core GPU, 16-core Neural Engine, 153GB/s bandwidth", "M5: CPU 10 lõi, GPU 8 hoặc 10 lõi, Neural Engine 16 lõi, băng thông 153GB/s"),
      memory: fact("16GB unified memory; configurable to 24GB or 32GB", "Bộ nhớ thống nhất 16GB; tùy chọn 24GB hoặc 32GB"),
      frontCamera: fact("12MP Center Stage camera with Desk View; 1080p", "Camera Center Stage 12MP có Desk View; 1080p"),
      audio: fact("Four-speaker system, Spatial Audio, three-microphone array, high-impedance headphone support", "Hệ thống bốn loa, Âm Thanh Không Gian, cụm ba micro, hỗ trợ tai nghe trở kháng cao"),
      battery: fact("Up to 18 hours video streaming or 15 hours wireless web", "Đến 18 giờ xem video trực tuyến hoặc 15 giờ duyệt web không dây"),
      charging: fact("MagSafe 3; fast charge with a 70W-or-higher USB‑C power source", "MagSafe 3; sạc nhanh với nguồn USB‑C từ 70W"),
      ports: fact("Two Thunderbolt 4 / USB 4 ports up to 40Gb/s, MagSafe 3, 3.5mm; supports up to two external displays", "Hai cổng Thunderbolt 4 / USB 4 đến 40Gb/s, MagSafe 3, 3,5 mm; hỗ trợ đến hai màn hình ngoài"),
      connectivity: "Wi‑Fi 7, Bluetooth 6, Thread",
      authentication: "Touch ID",
    },
  },
  "macbook-pro-m5": {
    introduced: "2025–2026",
    sourceUrl: "https://www.apple.com/macbook-pro/specs/",
    fields: {
      finishes: fact("Space Black or Silver", "Đen Không Gian hoặc Bạc"),
      capacity: "1TB / 2TB / 4TB / 8TB SSD (configuration dependent)",
      dimensions: fact("14-inch: 31.26 × 22.12 × 1.55 cm, 1.55–1.62 kg; 16-inch: 35.57 × 24.81 × 1.68 cm, 2.14–2.15 kg", "14 inch: 31,26 × 22,12 × 1,55 cm, 1,55–1,62 kg; 16 inch: 35,57 × 24,81 × 1,68 cm, 2,14–2,15 kg"),
      display: fact("14.2- or 16.2-inch Liquid Retina XDR, ProMotion up to 120Hz, 1600-nit peak HDR; nano-texture option", "Liquid Retina XDR 14,2 hoặc 16,2 inch, ProMotion đến 120Hz, HDR đỉnh 1.600 nit; tùy chọn nano-texture"),
      chip: fact("M5, M5 Pro or M5 Max; up to 18-core CPU, 40-core GPU, 16-core Neural Engine and 614GB/s bandwidth", "M5, M5 Pro hoặc M5 Max; tối đa CPU 18 lõi, GPU 40 lõi, Neural Engine 16 lõi và băng thông 614GB/s"),
      memory: fact("16GB to 128GB unified memory, depending on chip", "Bộ nhớ thống nhất 16GB đến 128GB, tùy chip"),
      frontCamera: fact("12MP Center Stage camera with Desk View; 1080p", "Camera Center Stage 12MP có Desk View; 1080p"),
      audio: fact("High-fidelity six-speaker system and studio-quality three-microphone array", "Hệ thống sáu loa độ trung thực cao và cụm ba micro chuẩn studio"),
      battery: fact("14-inch M5: up to 24 hours video / 16 hours web; battery results vary by size and chip", "Bản 14 inch M5: đến 24 giờ video / 16 giờ web; kết quả thay đổi theo kích thước và chip"),
      charging: fact("MagSafe 3; fast charge with 96W or higher on supported configurations", "MagSafe 3; sạc nhanh với nguồn từ 96W trên cấu hình hỗ trợ"),
      ports: fact("Three Thunderbolt 4 or 5 ports (by chip), HDMI, SDXC, MagSafe 3, 3.5mm", "Ba cổng Thunderbolt 4 hoặc 5 (tùy chip), HDMI, SDXC, MagSafe 3, 3,5 mm"),
      connectivity: fact("M5: Wi‑Fi 6E and Bluetooth 5.3; M5 Pro/Max: Wi‑Fi 7, Bluetooth 6 and Thread", "M5: Wi‑Fi 6E và Bluetooth 5.3; M5 Pro/Max: Wi‑Fi 7, Bluetooth 6 và Thread"),
      authentication: "Touch ID",
    },
  },
  "imac-m4": {
    introduced: "2024",
    sourceUrl: "https://www.apple.com/imac/specs/",
    fields: {
      finishes: fact("Blue, Purple, Pink, Orange, Yellow, Green, Silver", "Xanh Dương, Tím, Hồng, Cam, Vàng, Xanh Lá, Bạc"),
      capacity: "256GB / 512GB / 1TB / 2TB SSD",
      dimensions: fact("54.7 × 46.1 × 14.7 cm; 4.42–4.44 kg", "54,7 × 46,1 × 14,7 cm; 4,42–4,44 kg"),
      display: fact("23.5-inch 4.5K Retina, 4480×2520 at 218 ppi, P3, True Tone, 500 nits; nano-texture option", "Retina 4.5K 23,5 inch, 4480×2520, 218 ppi, P3, True Tone, 500 nit; tùy chọn nano-texture"),
      chip: fact("M4 with 8- or 10-core CPU, 8- or 10-core GPU, 16-core Neural Engine, 120GB/s bandwidth", "M4 với CPU 8 hoặc 10 lõi, GPU 8 hoặc 10 lõi, Neural Engine 16 lõi, băng thông 120GB/s"),
      memory: fact("16GB unified memory; configurable to 24GB or 32GB", "Bộ nhớ thống nhất 16GB; tùy chọn 24GB hoặc 32GB"),
      frontCamera: fact("12MP Center Stage camera with Desk View; 1080p", "Camera Center Stage 12MP có Desk View; 1080p"),
      audio: fact("High-fidelity six-speaker system with force-cancelling woofers; studio-quality three-microphone array", "Hệ thống sáu loa độ trung thực cao với woofer khử lực; cụm ba micro chuẩn studio"),
      ports: fact("Two or four Thunderbolt 4 / USB 4 ports, 3.5mm; Gigabit Ethernet standard or configurable", "Hai hoặc bốn cổng Thunderbolt 4 / USB 4, 3,5 mm; Gigabit Ethernet tiêu chuẩn hoặc tùy chọn"),
      connectivity: "Wi‑Fi 6E, Bluetooth 5.3",
      authentication: fact("Touch ID on included or configurable Magic Keyboard, depending on configuration", "Touch ID trên Magic Keyboard đi kèm hoặc tùy chọn, tùy cấu hình"),
    },
  },
  "mac-mini-m6": {
    introduced: "2026",
    sourceUrl: "https://www.apple.com/mac-mini/specs/",
    fields: {
      finishes: fact("Silver aluminum", "Nhôm màu Bạc"),
      capacity: "256GB / 512GB / 1TB / 2TB SSD; M5 Pro up to 8TB",
      dimensions: fact("12.7 × 12.7 × 5.0 cm; 0.67 kg (M6) or 0.73 kg (M5 Pro)", "12,7 × 12,7 × 5,0 cm; 0,67 kg (M6) hoặc 0,73 kg (M5 Pro)"),
      chip: fact("M6: 12-core CPU, 12-core GPU, Dual 16-core Neural Engine; optional M5 Pro up to 18-core CPU / 20-core GPU", "M6: CPU 12 lõi, GPU 12 lõi, Dual Neural Engine 16 lõi; tùy chọn M5 Pro đến CPU 18 lõi / GPU 20 lõi"),
      memory: fact("M6: 16GB, configurable to 24GB or 32GB; M5 Pro: 24GB, configurable to 48GB or 64GB", "M6: 16GB, tùy chọn 24GB hoặc 32GB; M5 Pro: 24GB, tùy chọn 48GB hoặc 64GB"),
      audio: fact("Built-in speaker; high-impedance 3.5mm headphone output; multichannel HDMI audio", "Loa tích hợp; ngõ tai nghe 3,5 mm hỗ trợ trở kháng cao; âm thanh đa kênh qua HDMI"),
      ports: fact("Front: two USB‑C 10Gb/s and 3.5mm. Rear: HDMI, 2.5Gb Ethernet, three Thunderbolt 4 (M6) or Thunderbolt 5 (M5 Pro)", "Trước: hai USB‑C 10Gb/s và 3,5 mm. Sau: HDMI, Ethernet 2,5Gb, ba Thunderbolt 4 (M6) hoặc Thunderbolt 5 (M5 Pro)"),
      connectivity: "Wi‑Fi 7, Bluetooth 6, Thread, 2.5Gb Ethernet (10Gb configurable)",
    },
  },
  "mac-studio-m5": {
    introduced: "2026",
    sourceUrl: "https://www.apple.com/mac-studio/specs/",
    fields: {
      finishes: fact("Silver aluminum", "Nhôm màu Bạc"),
      capacity: "512GB–8TB SSD (M5 Max); 1TB–16TB SSD (M5 Ultra)",
      dimensions: fact("19.7 × 19.7 × 9.5 cm; 2.7 kg (M5 Max) or 3.6 kg (M5 Ultra)", "19,7 × 19,7 × 9,5 cm; 2,7 kg (M5 Max) hoặc 3,6 kg (M5 Ultra)"),
      chip: fact("M5 Max up to 18-core CPU / 40-core GPU; M5 Ultra up to 36-core CPU / 80-core GPU", "M5 Max đến CPU 18 lõi / GPU 40 lõi; M5 Ultra đến CPU 36 lõi / GPU 80 lõi"),
      memory: fact("M5 Max: 36GB–128GB; M5 Ultra: 96GB–512GB unified memory", "Bộ nhớ thống nhất M5 Max: 36GB–128GB; M5 Ultra: 96GB–512GB"),
      audio: fact("Built-in speaker, high-impedance 3.5mm output and multichannel HDMI audio", "Loa tích hợp, ngõ 3,5 mm hỗ trợ trở kháng cao và âm thanh đa kênh qua HDMI"),
      ports: fact("Four rear Thunderbolt 5, two USB‑A, HDMI 2.1, 10Gb Ethernet, 3.5mm; two front USB‑C or Thunderbolt 5 plus SDXC", "Bốn Thunderbolt 5 phía sau, hai USB‑A, HDMI 2.1, Ethernet 10Gb, 3,5 mm; hai USB‑C hoặc Thunderbolt 5 phía trước cùng SDXC"),
      connectivity: "Wi‑Fi 7, Bluetooth 6, Thread, 10Gb Ethernet",
    },
  },
  "mac-pro-m2-ultra": {
    introduced: "2023",
    sourceUrl: "https://support.apple.com/en-us/111343",
    fields: {
      finishes: fact("Silver; tower with feet, configurable with wheels", "Bạc; dạng tower có chân, tùy chọn bánh xe"),
      capacity: "1TB / 2TB / 4TB / 8TB SSD",
      dimensions: fact("52.9 × 21.8 × 45.0 cm; 16.86 kg; height with wheels 55.7 cm", "52,9 × 21,8 × 45,0 cm; 16,86 kg; cao 55,7 cm khi gắn bánh xe"),
      chip: fact("M2 Ultra: 24-core CPU, 60- or 76-core GPU, 32-core Neural Engine, 800GB/s bandwidth", "M2 Ultra: CPU 24 lõi, GPU 60 hoặc 76 lõi, Neural Engine 32 lõi, băng thông 800GB/s"),
      memory: fact("64GB unified memory; configurable to 128GB or 192GB", "Bộ nhớ thống nhất 64GB; tùy chọn 128GB hoặc 192GB"),
      audio: fact("Built-in speaker, high-impedance 3.5mm output and multichannel HDMI audio", "Loa tích hợp, ngõ 3,5 mm hỗ trợ trở kháng cao và âm thanh đa kênh qua HDMI"),
      ports: fact("Eight Thunderbolt 4, two USB‑A, two HDMI, two 10Gb Ethernet, 3.5mm; six PCIe Gen 4 full-length slots", "Tám Thunderbolt 4, hai USB‑A, hai HDMI, hai Ethernet 10Gb, 3,5 mm; sáu khe PCIe Gen 4 toàn chiều dài"),
      connectivity: "Wi‑Fi 6E, Bluetooth 5.3, dual 10Gb Ethernet",
      accessories: fact("Magic Keyboard with Touch ID and Numeric Keypad, Magic Mouse, power cord and USB‑C charge cable", "Magic Keyboard có Touch ID và bàn phím số, Magic Mouse, dây nguồn và cáp sạc USB‑C"),
    },
  },
} as const satisfies Pick<ProductTechnicalSpecCatalog, MacModel>;
